name: pkgdown

on:
  push:
    branches:
      - master # or your default branch

jobs:
  pkgdown:
    runs-on: ubuntu-latest #or macOS-latest, windows-latest.

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install GMP
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp3-dev r-cran-pkgdown

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Build pkgdown site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
